# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: push

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pre dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq libxml2-dev libxmlsec1-dev libxmlsec1-openssl
            pip install wheel==0.34.2 pip==24.0 setuptools==44.0.0
            pip install pytest
            pip install -r requirements.txt --force-reinstall --no-binary signxml,xmlsec
